/// Категории автозапчастей для сетки на главном каталоге.
/// icon — имя файла в assets/parts/ (например filters.png).
final List<Map<String, String>> autoCategories = [
  {"name": "Расходники и ТО", "icon": "filters.png"},
  {"name": "Тормозная система", "icon": "brakes.png"},
  {"name": "Подвеска и рулевое", "icon": "suspension.png"},
  {"name": "Двигатель", "icon": "engine.png"},
  {"name": "Трансмиссия", "icon": "gearbox.png"},
  {"name": "Система охлаждения", "icon": "cooling.png"},
  {"name": "Электрика", "icon": "electric.png"},
  {"name": "Освещение", "icon": "lights.png"},
  {"name": "Кузовные детали", "icon": "body.png"},
  {"name": "Масла и химия", "icon": "oil.png"},
  {"name": "Аккумуляторы", "icon": "battery.png"},
  {"name": "Шины и диски", "icon": "wheels.png"},
  {"name": "Выхлопная система", "icon": "exhaust.png"},
  {"name": "Топливная система", "icon": "fuel.png"},
  {"name": "Зажигание", "icon": "spark.png"},
  {"name": "Кондиционер", "icon": "ac.png"},
  {"name": "Инструменты", "icon": "tools.png"},
  {"name": "Аксессуары", "icon": "accs.png"},
  {"name": "Автозвук", "icon": "audio.png"},
  {"name": "Стеклоочистители", "icon": "wipers.png"},
  {"name": "Крепеж и клипсы", "icon": "clips.png"},
];
