name: bloomp
description: Маркетплейс автозапчастей
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.1.2
  google_fonts: ^6.2.1
  fl_chart: ^0.66.2
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  camera: ^0.10.5
  google_mlkit_text_recognition: ^0.11.0
  scrollable_positioned_list: ^0.3.2
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/png/
    - assets/parts/
